### PR TITLE
Simple gameloop

### PR DESCRIPTION
**Pull request by Lumipallo**

### CODE REVIEW

**Comment by Anonyymi** [comment]
I'm sorry but this is way too messy to be merged to master as-is.

And what's the current benefit of this whole 'system'? If we are going for a multithreaded game engine then I think the structure should be planned carefully, this is just complicating things at the moment with very little to no benefit.

Some things I dislike;
* Game headers (h) and source (cpp) files in separate folders, why?
* CMakeLists.txt no longer MSVC compatible, I don't think as radical changes are needed for unix compability
* SDL2 was included in the repo for Windows compability. It's easier to just ship the repo with the library files for windows users. I had set-up the cmakelists so that those will not be included/linked against on *nix.
* What does even "Hebi" stand for? The whole system inside the Hebi.* files is a mess, honestly.

Some things I like;
* The gameloop is simple. The separation between FPS and UPS is simple. That I do like, but I don't think this is acceptable as-is.

So all in all, if you expect me to waste time cleaning up someone else's mess, you're wrong. Lets keep the project clean and simple, what is clean and simple is a bit subjective then again but I think this certainly isn't at least clean/clear.

**Comment by Lumipallo** [comment]
I placed headers and sources to separate folder to make file structure cleaner. Otherwise everything would be cluttered in same folder.
I reduced CMakeLists.txt to bare minimum for my own purposes. It works for me and I had no intentions of being merged as is. It didn't originally work for linux so I had do it.
SDL was removed because I didn't need it and thought it was out of place. It could be included in some folder called "win32" to directly separate for windows only.
Hebi means snake and is a pun, it handles giving tasks to threads. It is a mess I know but it works.

I'm not expecting you to clean my stuff. You wanted to see my work and i provided it as is. Please keep in mind that there is still a LOT to do. This is barely a skeleton.

**Comment by Anonyymi** [comment]
When we merge I will restructure the folders and files back to original state. I will also take the current CMakeLists.txt (my version) and edit it to work on *nix and replace yours with that.

What was the problem with SDL_mixer you were having? Why it wouldn't work?

**Comment by Lumipallo** [comment]
SDL_mixer caused problems for me and I didn't want to resolve them then. It's a minor thing so I didn't want to spend time on it.
C-style is best style for prototyping (for me). I know it and am comfortable using it to make things quickly. C++ for me is C + classes and some other occasionally useful stuff. There is no other reason for it.

**Pull request closed without merging**
